<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class SurveyQuestionsTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {
        

        \DB::table('survey_questions')->delete();
        
        \DB::table('survey_questions')->insert(array (
            0 => 
            array (
                'id' => 1,
                'question_set_id' => 1,
                'question' => 'This Is a Test Questionaaaa',
                'option1' => 'Excellent A',
                'point1' => 4,
                'option2' => 'Good A',
                'point2' => 3,
                'option3' => 'Average A',
                'point3' => 2,
                'option4' => 'Bad A',
                'point4' => 1,
                'created_at' => '2023-12-20 18:57:26',
                'updated_at' => '2023-12-20 21:08:22',
            ),
            1 => 
            array (
                'id' => 2,
                'question_set_id' => 2,
                'question' => 'Rate the faculty member\'s commitment to pursuing professional development opportunities.',
                'option1' => 'Very Well',
                'point1' => 4,
                'option2' => 'Well',
                'point2' => 3,
                'option3' => 'Average',
                'point3' => 2,
                'option4' => 'Bed',
                'point4' => 1,
                'created_at' => '2023-12-20 18:58:41',
                'updated_at' => '2023-12-20 22:06:11',
            ),
            2 => 
            array (
                'id' => 3,
                'question_set_id' => 1,
                'question' => 'Provide feedback on the employee\'s ability to mentor and support team members.',
                'option1' => 'Very Well',
                'point1' => 4,
                'option2' => 'Good',
                'point2' => 3,
                'option3' => 'Average',
                'point3' => 2,
                'option4' => 'Not Supportive',
                'point4' => 1,
                'created_at' => '2023-12-20 21:09:06',
                'updated_at' => '2023-12-20 21:09:06',
            ),
            3 => 
            array (
                'id' => 4,
                'question_set_id' => 2,
                'question' => 'Evaluate the faculty member\'s participation in departmental committees and university-wide initiatives.',
                'option1' => 'Very actively participates',
                'point1' => 4,
                'option2' => 'Occasionally participates',
                'point2' => 2,
                'option3' => 'Moderately participates',
                'point3' => 3,
                'option4' => 'Rarely participates',
                'point4' => 1,
                'created_at' => '2023-12-20 21:58:36',
                'updated_at' => '2023-12-20 21:58:36',
            ),
            4 => 
            array (
                'id' => 5,
                'question_set_id' => 2,
                'question' => 'Rate the faculty member\'s ability to collaborate with colleagues on research or teaching initiatives.',
                'option1' => 'Very Good',
                'point1' => 4,
                'option2' => 'Good',
                'point2' => 3,
                'option3' => 'Average',
                'point3' => 2,
                'option4' => 'Bed',
                'point4' => 1,
                'created_at' => '2023-12-20 22:01:26',
                'updated_at' => '2023-12-20 22:01:26',
            ),
            5 => 
            array (
                'id' => 6,
                'question_set_id' => 2,
                'question' => 'Evaluate the faculty member\'s effectiveness in communicating departmental goals and expectations.',
                'option1' => 'Very effective',
                'point1' => 4,
                'option2' => 'Effective',
                'point2' => 3,
                'option3' => 'Average',
                'point3' => 2,
                'option4' => 'Not Effective',
                'point4' => 1,
                'created_at' => '2023-12-20 22:02:41',
                'updated_at' => '2023-12-20 22:02:41',
            ),
            6 => 
            array (
                'id' => 7,
                'question_set_id' => 2,
                'question' => 'Assess the faculty member\'s ability to adapt to changes in curriculum or teaching methodologies.',
                'option1' => 'Very Well',
                'point1' => 4,
                'option2' => 'Well',
                'point2' => 3,
                'option3' => 'Average',
                'point3' => 2,
                'option4' => 'Bed',
                'point4' => 1,
                'created_at' => '2023-12-20 22:03:48',
                'updated_at' => '2023-12-20 22:03:48',
            ),
            7 => 
            array (
                'id' => 8,
                'question_set_id' => 2,
                'question' => 'Assess the faculty member\'s contribution to scholarly publications or research projects.',
                'option1' => 'Exceptional',
                'point1' => 4,
                'option2' => 'Outstanding',
                'point2' => 3,
                'option3' => 'Satisfactory',
                'point3' => 2,
                'option4' => 'Inadequate',
                'point4' => 1,
                'created_at' => '2023-12-20 22:05:28',
                'updated_at' => '2023-12-20 22:05:28',
            ),
            8 => 
            array (
                'id' => 9,
                'question_set_id' => 1,
                'question' => 'How would you rate the supervisor\'s ability to provide effective leadership and make sound decisions?',
                'option1' => 'Very Well',
                'point1' => 4,
                'option2' => 'Well',
                'point2' => 3,
                'option3' => 'Satisfactory',
                'point3' => 2,
                'option4' => 'Bed',
                'point4' => 1,
                'created_at' => '2023-12-20 22:07:18',
                'updated_at' => '2023-12-20 22:07:18',
            ),
            9 => 
            array (
                'id' => 10,
                'question_set_id' => 1,
                'question' => 'Rate the supervisor\'s communication skills, including the clarity of instructions and the frequency of feedback.',
                'option1' => 'Very Well',
                'point1' => 4,
                'option2' => 'Well',
                'point2' => 3,
                'option3' => 'Average',
                'point3' => 2,
                'option4' => 'Bed',
                'point4' => 1,
                'created_at' => '2023-12-20 22:08:15',
                'updated_at' => '2023-12-20 22:08:15',
            ),
            10 => 
            array (
                'id' => 11,
                'question_set_id' => 1,
                'question' => 'Evaluate the level of support and mentorship provided by the supervisor in your professional development.',
                'option1' => 'Very Well',
                'point1' => 4,
                'option2' => 'Well',
                'point2' => 3,
                'option3' => 'Average',
                'point3' => 2,
                'option4' => 'Not Supportive',
                'point4' => 1,
                'created_at' => '2023-12-20 22:09:22',
                'updated_at' => '2023-12-20 22:09:22',
            ),
            11 => 
            array (
                'id' => 12,
                'question_set_id' => 1,
                'question' => 'How well does the supervisor recognize and appreciate your contributions to the team or projects?',
                'option1' => 'Very Well',
                'point1' => 4,
                'option2' => 'Well',
                'point2' => 3,
                'option3' => 'Average',
                'point3' => 2,
                'option4' => 'Bed',
                'point4' => 1,
                'created_at' => '2023-12-20 22:11:01',
                'updated_at' => '2023-12-20 22:11:01',
            ),
            12 => 
            array (
                'id' => 13,
                'question_set_id' => 1,
                'question' => 'To what extent does the supervisor empower you with the autonomy to take on challenging tasks and projects?',
                'option1' => 'Very Frequent',
                'point1' => 4,
                'option2' => 'Frequent',
                'point2' => 3,
                'option3' => 'Moderately',
                'point3' => 2,
                'option4' => 'Rarely',
                'point4' => 1,
                'created_at' => '2023-12-20 22:18:55',
                'updated_at' => '2023-12-20 22:18:55',
            ),
            13 => 
            array (
                'id' => 14,
                'question_set_id' => 5,
                'question' => 'How would you rate the overall effectiveness of the teacher in helping you understand and learn the course material?',
                'option1' => 'Very Well',
                'point1' => 4,
                'option2' => 'Well',
                'point2' => 3,
                'option3' => 'Average',
                'point3' => 2,
                'option4' => 'Bed',
                'point4' => 1,
                'created_at' => '2023-12-20 22:41:45',
                'updated_at' => '2023-12-20 22:41:45',
            ),
            14 => 
            array (
                'id' => 15,
                'question_set_id' => 5,
                'question' => 'Rate the teacher\'s ability to communicate complex concepts clearly and effectively.',
                'option1' => 'Very Well',
                'point1' => 4,
                'option2' => 'Well',
                'point2' => 3,
                'option3' => 'Average',
                'point3' => 2,
                'option4' => 'Bed',
                'point4' => 1,
                'created_at' => '2023-12-20 22:42:38',
                'updated_at' => '2023-12-20 22:42:38',
            ),
            15 => 
            array (
                'id' => 16,
                'question_set_id' => 5,
                'question' => 'To what extent does the teacher engage and interact with students during lectures and discussions?',
                'option1' => 'Very Frequently',
                'point1' => 4,
                'option2' => 'Moderately',
                'point2' => 3,
                'option3' => 'Occasionally',
                'point3' => 2,
                'option4' => 'Rarely',
                'point4' => 1,
                'created_at' => '2023-12-20 22:44:29',
                'updated_at' => '2023-12-20 22:44:29',
            ),
            16 => 
            array (
                'id' => 17,
                'question_set_id' => 5,
                'question' => 'How accessible and approachable is the teacher for questions, concerns, or additional help outside of class?',
                'option1' => 'Very accessible',
                'point1' => 4,
                'option2' => 'Accessible',
                'point2' => 3,
                'option3' => 'Average',
                'point3' => 2,
                'option4' => 'Not accessible',
                'point4' => 1,
                'created_at' => '2023-12-20 22:45:40',
                'updated_at' => '2023-12-20 22:45:40',
            ),
            17 => 
            array (
                'id' => 18,
                'question_set_id' => 5,
                'question' => 'To what extent does the teacher incorporate innovative teaching methods and technologies into the classroom?',
                'option1' => 'Very Frequently',
                'point1' => 4,
                'option2' => 'Moderately',
                'point2' => 3,
                'option3' => 'Occasionally',
                'point3' => 2,
                'option4' => 'Rarely',
                'point4' => 1,
                'created_at' => '2023-12-20 22:48:14',
                'updated_at' => '2023-12-20 22:48:14',
            ),
            18 => 
            array (
                'id' => 19,
                'question_set_id' => 5,
                'question' => 'How fair and objective do you perceive the teacher to be in grading and evaluating student performance?',
                'option1' => 'Extremely fair',
                'point1' => 4,
                'option2' => 'Fair',
                'point2' => 3,
                'option3' => 'Somewhat fair',
                'point3' => 2,
                'option4' => 'Unfair',
                'point4' => 1,
                'created_at' => '2023-12-20 22:49:49',
                'updated_at' => '2023-12-20 22:49:49',
            ),
            19 => 
            array (
                'id' => 20,
                'question_set_id' => 3,
                'question' => 'How would you rate the department teacher\'s communication skills in conveying information clearly and effectively?',
                'option1' => 'Very Well',
                'point1' => 4,
                'option2' => 'Well',
                'point2' => 3,
                'option3' => 'Average',
                'point3' => 2,
                'option4' => 'Bed',
                'point4' => 1,
                'created_at' => '2023-12-20 22:54:21',
                'updated_at' => '2023-12-20 22:54:21',
            ),
            20 => 
            array (
                'id' => 21,
                'question_set_id' => 3,
                'question' => 'How approachable do you find the department teacher for discussions, questions, or concerns?',
                'option1' => 'Very Well',
                'point1' => 4,
                'option2' => 'Well',
                'point2' => 3,
                'option3' => 'Occasionally',
                'point3' => 2,
                'option4' => 'Rarely',
                'point4' => 1,
                'created_at' => '2023-12-20 22:55:32',
                'updated_at' => '2023-12-20 22:55:32',
            ),
            21 => 
            array (
                'id' => 22,
                'question_set_id' => 3,
                'question' => 'How approachable do you find the department teacher for discussions, questions, or concerns?',
                'option1' => 'Very Well',
                'point1' => 4,
                'option2' => 'Well',
                'point2' => 3,
                'option3' => 'Average',
                'point3' => 2,
                'option4' => 'Bed',
                'point4' => 1,
                'created_at' => '2023-12-20 22:56:13',
                'updated_at' => '2023-12-20 22:56:13',
            ),
            22 => 
            array (
                'id' => 23,
                'question_set_id' => 3,
                'question' => 'To what extent does the department teacher take on leadership roles or initiatives within the department?',
                'option1' => 'Very Well',
                'point1' => 4,
                'option2' => 'Well',
                'point2' => 3,
                'option3' => 'Average',
                'point3' => 2,
                'option4' => 'Bed',
                'point4' => 1,
                'created_at' => '2023-12-20 22:56:48',
                'updated_at' => '2023-12-20 22:56:48',
            ),
            23 => 
            array (
                'id' => 24,
                'question_set_id' => 3,
                'question' => 'How well does the department teacher adapt to changes in the academic environment or departmental policies?',
                'option1' => 'Very Well',
                'point1' => 4,
                'option2' => 'Well',
                'point2' => 3,
                'option3' => 'Average',
                'point3' => 2,
                'option4' => 'Bed',
                'point4' => 1,
                'created_at' => '2023-12-20 22:57:29',
                'updated_at' => '2023-12-20 22:57:29',
            ),
            24 => 
            array (
                'id' => 25,
                'question_set_id' => 3,
                'question' => 'Provide feedback on the employee\'s ability to mentor and support team members.',
                'option1' => 'Very Good',
                'point1' => 4,
                'option2' => 'Good',
                'point2' => 3,
                'option3' => 'Average',
                'point3' => 2,
                'option4' => 'Bed',
                'point4' => 1,
                'created_at' => '2023-12-20 22:58:05',
                'updated_at' => '2023-12-20 22:58:05',
            ),
        ));
        
        
    }
}